django:
  debug: true
  hostname: consentmanager-develop.inpecotpm.com,consentmanager
  secret_key: "z&5*03u@zh9p@gvkc@r@xu#abpodi_5&hbp4#)7k(&gz7a^#t@"
  timezone: "Europe/Rome"
  database:
    engine: postgresql
    host: "hgw-develop-db.postgres.database.azure.com"
    name: "hgw_consent_manager"
    password: "vV9CeB9f|=|PVRG@rR|$gFELy"
    port: 5432
    user: "hgw_consent_manager@hgw-develop-db"

logging:
  level: DEBUG

saml:
  service: tscns
  idp_url: "https://tscns-develop.inpecotpm.com/idp/shibboleth"
  sp_name: Consent Manager Service Provider
  sp_cert: /container/service/saml2/saml2.cert.pem
  sp_key: /container/service/saml2/saml2.key.pem

notification:
  type: 'kafka'
  kafka:
    uri: kafka:9092
    topic: consent-manager-notification
    ssl: false
    ca_cert: /container/client_certs/kafka.chain.cert.pem
    client_cert: /container/client_certs/cert.pem
    client_key: /container/client_certs/key.pem