django:
  debug: false
  secret_key: i*w3i*-y589ynfl_sar!h9r1mpra8mkjpwobeage5h5a(0x!d$
  hostname: consentmanager
  port: 8002
  timezone: Europe/Rome
  database:
    engine: postgresql
    host: "localhost"
    name: "consentmanager"
    password: "consentmanager"
    port: 5432
    user: "consentmanager"

logging:
  level: DEBUG

saml:
  service: tscns
  idp_url: https://tscns/idp/shibboleth
  sp_name: Consent Manager Service Provider
  sp_cert: ../saml2/saml2.cert.pem
  sp_key: ../saml2/saml2.key.pem

notification:
  type: 'kafka'
  kafka:
    uri: kafka:9092
    topic: consent_manager_notification
    ssl: false
    ca_cert: ../../docker/kafkaclientcerts/kafka.chain.cert.pem
    client_cert: ../../docker/kafkaclientcerts/cert.pem
    client_key: ../../docker/kafkaclientcerts/key.pem
