# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hgw_backend.models
import oauth2_provider.generators
import oauth2_provider.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hgw_common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('token_type', models.CharField(max_length=10)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(upload_to='')),
                ('key', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OAuth2Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_url', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=40)),
                ('client_secret', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'OAuth2 Authentication',
            },
        ),
        migrations.CreateModel(
            name='RESTClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated', validators=[oauth2_provider.validators.validate_uris])),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials')], max_length=32)),
                ('client_secret', models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('client_role', models.CharField(choices=[('ST', 'STANDARD'), ('SU', 'SUPER')], default='STANDARD', max_length=2)),
                ('scopes', models.CharField(default='messages:write', help_text='Space separated scopes to assign to the REST client', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(default=hgw_backend.models.get_source_id, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', hgw_backend.models.HostnameURLField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hgw_common.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='restclient',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hgw_backend.Source'),
        ),
        migrations.AddField(
            model_name='restclient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hgw_backend_restclient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='oauth2_authentication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgw_backend.OAuth2Authentication'),
        ),
    ]
