# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hgw_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.FileField(upload_to='')),
                ('key', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(default=hgw_backend.models.get_source_id, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', hgw_backend.models.CustomURLField()),
                ('auth_type', models.CharField(choices=[('C', 'Certificates'), ('O', 'OAuth2')], default=('C', 'Certificates'), max_length=3)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
