# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2authentication',
            name='auth_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='oauth2authentication',
            name='auth_username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='oauth2authentication',
            name='basic_auth',
            field=models.BooleanField(default=False),
        ),
    ]
