# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hgw_common.fields
import hgw_common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_url', models.CharField(max_length=200, unique=True)),
                ('access_token', models.CharField(max_length=1024)),
                ('token_type', models.CharField(max_length=10)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(default=hgw_common.models.generate_id, max_length=32)),
                ('source_id', models.CharField(max_length=32)),
                ('destination_id', models.CharField(max_length=32)),
                ('person_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=30)),
                ('payload', models.CharField(max_length=1000, validators=[hgw_common.fields.JSONValidator])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('code', 'version')]),
        ),
        migrations.AddField(
            model_name='channel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgw_common.Profile'),
        ),
    ]
