# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hgw_common.models
import hgw_common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_url', models.CharField(max_length=200, unique=True)),
                ('access_token', models.CharField(max_length=1024)),
                ('token_type', models.CharField(max_length=10)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('coding_system', models.CharField(max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hgw_common.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('coding_system', models.CharField(max_length=10)),
                ('profile_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='hgw_common.ProfileDomain')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('code', 'version')]),
        ),
    ]
