# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=1500)),
                ('reason', models.CharField(max_length=10)),
                ('retry', models.BooleanField(help_text='Boolean indicating if the message delivery should be retried')),
            ],
        ),
    ]
