django:
  debug: true
  secret_key: 8m#4t%c_z1l7=gsfpf=han8ibdmd-+w1-05^&-+e4%)vwn2*7@
  hostname: hgwfrontend,localhost
  port: 8000
  request_validity_seconds: 60
  timezone: Europe/Rome
  database:
    engine: sqlite3
    name: ../hgw_frontend_db.sqlite3
    failure_exp_retry_base_period_sec: 2
    failure_max_retry_wait: 5

logging:
  level: DEBUG

saml:
  service: tscns
  idp_url: https://tscns/idp/shibboleth
  sp_name: HGW Frontend Service Provider
  sp_cert: ../../docker/saml2certs/saml2.cert.pem
  sp_key: ../../docker/saml2certs/saml2.key.pem

consent_manager:
  uri: https://consentmanager:8002
  client_id: 04hpKQ1RPdbQAI0TYZ4A162r0IBlPH8WS6cZ5BMR
  client_secret: NrRetjwS3n9By6FhqWKbkuGLTvuQWtbQq3QwnKc8CgHoJg02MeQI4Mitj2fISJXv4DQieaIhdyWLy5Klf30i37mP7P0Vh3acOGJZFaHhKuBI3QYlRJBGipm50bBR3zfD

hgw_backend:
  uri: https://hgwbackend:8003
  client_id: Z3p4Q2La14DItTBz9fxFBY4vflHPYMLLeXoUltOt
  client_secret: ptyQgSdx9r0QZNntI3q1F1ZwT9fZU0aijGkZqRkAyibEF5qNaSIxwIFEsYV1L0rBD9a1ALCmVqC6ERw7sK4qcfk57oUrkFOOhUs5JUHnIcQ2A6rJ5c2tcIQUsJLfcQLI

kafka:
  uri: kafka:9093
  ssl: false
  ca_cert: ../../docker/kafkaclientcerts/kafka.chain.cert.pem
  client_cert: ../../docker/kafkaclientcerts/cert.pem
  client_key: ../../docker/kafkaclientcerts/key.pem
