django:
  debug: true
  secret_key: 5ed9#sef91*#bn+etd6ug*ty6)iysxmcnl%qv3c+i&-1ec1644
  hostname: hgwbackend
  port: 8003
  timezone: Europe/Rome
  database:
    engine: sqlite3
    name: ../hgw_backend_db.sqlite3
    failure_exp_retry_base_period_sec: 2
    failure_max_retry_wait: 5

logging:
  level: DEBUG

kafka:
  uri: kafka:9093
  ssl: true
  ca_cert: ../../docker/kafkaclientcerts/kafka.chain.cert.pem
  client_cert: ../../docker/kafkaclientcerts/cert.pem
  client_key: ../../docker/kafkaclientcerts/key.pem
