# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=32, unique=False)),
                ('flow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='hgw_frontend.FlowRequest')),
                ('status', models.CharField(choices=[('CR', 'CONSENT_REQUESTED'), ('AC', 'ACTIVE')], max_length=2)),
            ],
        ),
    ]
