# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-31 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrequest',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgw_common.Profile'),
        ),
    ]
