# Generated by Django 2.2.5 on 2019-09-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='expire_validity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='start_validity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='flow_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hgw_frontend.FlowRequest'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hgw_frontend.Source'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[('CR', 'CONSENT_REQUESTED'), ('WS', 'WAITING_SOURCE_NOTIFICATION'), ('AC', 'ACTIVE'), ('CV', 'CONSENT_REVOKED')], max_length=2),
        ),
        migrations.AlterField(
            model_name='flowrequest',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hgw_frontend.Destination'),
        ),
        migrations.AlterField(
            model_name='hgwfrontenduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hgw_common.Profile'),
        ),
    ]
