# Generated by Django 2.2.5 on 2019-12-20 12:24

from django.db import migrations, models


def migrate__consent_aborted__channel_status(apps, schema_editor):
    """
    Channel status CONSENT_ABORTED has been migrated from 'AB' to 'CA'
    """
    Channel = apps.get_model('hgw_frontend', 'Channel')
    for ch in Channel.objects.filter(status='AB').all():
        ch.status = 'CA'
        ch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_frontend', '0002_add_channel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[
                ('CR', 'CONSENT_REQUESTED'),
                ('WS', 'WAITING_SOURCE_NOTIFICATION'),
                ('AC', 'ACTIVE'),
                ('AB', 'ABORTED'), # this is temporarily renamed for migration
                ('CV', 'CONSENT_REVOKED'),
                ('CA', 'CONSENT_ABORTED'),
                ('IA', 'IDP_ABORTED')], max_length=2),
        ),
        migrations.RunPython(migrate__consent_aborted__channel_status),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[
                ('CR', 'CONSENT_REQUESTED'),
                ('WS', 'WAITING_SOURCE_NOTIFICATION'),
                ('AC', 'ACTIVE'),
                ('CV', 'CONSENT_REVOKED'),
                ('CA', 'CONSENT_ABORTED'),
                ('IA', 'IDP_ABORTED')], max_length=2),
        ),
    ]
