# Generated by Django 2.2.5 on 2020-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_frontend', '0003_abort_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentconfirmation',
            name='destination_endpoint_callback_url',
            field=models.CharField(max_length=2048),
        ),
    ]
