# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hgw_common', '0001_initial'),
        ('hgw_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRequestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgw_frontend.FlowRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True))
            ],
        ),
        migrations.AddField(
            model_name='flowrequestsource',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hgw_frontend.Source'),
        ),
    ]
